[versions]
gradle-plugin-publish = "1.3.0"
nexus-publish = "2.0.0"
spotless = "7.0.2"
assertj = "3.27.3"
commons-io = "2.18.0"
freemarker = "2.3.34"
twirl = "2.0.3"
mockito = "5.15.2"
kotlin-plugin = "2.1.10"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
