name: Publish

on:
  push:
    branches: # Snapshots
      - 2.9.x
    tags: ["**"] # Releases

permissions:
  contents: read # for checkout

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v3
    with:
      extra-coursier-cache-key: "publish"
    secrets: inherit
